VERSION = 0
INSTALL_BIN_DIR = ${PREFIX}/bin
INSTALL_LIB_DIR = ${PREFIX}/lib/wcc/${VERSION}
INSTALL_LIB_INCLUDE_DIR = ${INSTALL_LIB_DIR}/include

WCC_BUILD_FLAGS := -D INSTALL_LIB_DIR='"${INSTALL_LIB_DIR}"'

WCC_BIN = ${SIR_DIR}/wcc
WCC_RUN_FLAGS := -I ${SIR_DIR}/include
